config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  
  resources :employees

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    def index
        @employees_data = Employee.all
        @employees=Hash new
        @employees_data.each do |employee_data|
            if @employees.has_key?(employee_data[:lead_name])
                @employees[employee_data[:lead_name]].push({"name":employee_data[:name],"skills":employee_data[:skills].split(',').length})
            else
                @employees[employee_data[:lead_name]]=[]
                @employees[employee_data[:lead_name]].push({"name":employee_data[:name],"skills":employee_data[:skills].split(',').length})
            end
        end
        @employees.each do |k,v| 
            puts k
            puts v
            @employees[k]=v.sort_by { |ob| ob[:skills] }.reverse
        end
        @lead_names=@employees.keys
        puts @employees

        
    end

    def show
        @employee = Employee.find(params[:id])
        puts @employee
    end
    
    def new
    end
    
    def create
        @employee = Employee.new(employee_params)
        @employee.save
        redirect_to @employee
    end
    
    private
        def employee_params
            params.require(:employee).permit(:name,:project_name,:lead_name,:skills)
        end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/employees/index.html.erb
<% @lead_names.each do |lead_name| %>
Team Lead: <%= lead_name %>
<br><br>
<table>
  <tr>
    <th>Name</th>
    <th>Skills</th>
    <th colspan="2"></th>
  </tr>
  <% @employees[lead_name].each do |employee_data| %>
    <tr>
      <td><%= employee_data[:name] %></td>
      <td><%= employee_data[:skills] %></td>
    </tr>
  <% end %>
</table>
<br><br>
<% end %>
<br><br>

<%= link_to 'Add New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= form_with scope: :employee, url: employees_path,local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :project_name %><br>
    <%= form.select :project_name, ["RG", "TC", "RAVEN", "SAMPLE", "Other"], :prompt => 'Select One',:class => 'genForm_dropBox' %>
  </p>
 <p>
    <%= form.label :lead_name %><br>
    <%= form.select :lead_name, ["vivek","test lead","test1 lead","s1 lead","s2 lead","kranthi"], :prompt => 'Select One',:class => 'genForm_dropBox' %>
  </p>
  <p>
    <%= form.label :skills %><br>
    <%= form.text_field :skills %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
<br><br>
<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @employee[:name] %>
</p>
 
<p>
  <strong>Project Name:</strong>
  <%= @employee[:project_name] %>
</p>

<p>
  <strong>Lead Name:</strong>
  <%= @employee[:lead_name] %>
</p>
 
<p>
  <strong>skills:</strong>
  <%= @employee[:skills] %>
</p>
<br><br>
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello User</h1>
<br><br>
<%= link_to 'My App', controller: 'employees' %>